IMG_SRC=img_cnn_classifier
V_SRC=voice_nn_classifier
PREDICT_SRC=predict

img:
	python3.6 $(IMG_SRC).py

voice:
	python3.6 $(V_SRC).py

all:
	python3.6 $(IMG_SRC).py
	python3.6 $(V_SRC).py
	python3.6	$(PREDICT_SRC).py

predict:
	python3.6	$(PREDICT_SRC).py
